send USR2 signal to resque for restart

diff --git a/recipes/templates/resque.erb b/recipes/templates/resque.erb
--- a/recipes/templates/resque.erb
+++ b/recipes/templates/resque.erb
@@ -44,7 +44,12 @@ force-stop)
   sig TERM && exit 0
   echo >&2 "Not running"
   ;;
-restart|reload)
+restart)
+  sig USR2 && echo restarted OK && exit 0
+  echo >&2 "Couldn't restart, starting resque workers instead"
+  run "$CMD"
+  ;;
+reload)
   sig HUP && echo reloaded OK && exit 0
   echo >&2 "Couldn't reload, starting resque workers instead"
   run "$CMD"
